name: Fetch Teemo Data

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todo dia às 3h UTC
  workflow_dispatch:     # Permite rodar manualmente também

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch_teemo.py
        run: python scripts/fetch_teemo.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/teemo.json
          git commit -m "Update Teemo data"
          git push
