name: Update Teemo Stats

on:
  schedule:
    - cron: '0 */6 * * *' # A cada 6 horas
  workflow_dispatch:

jobs:
  fetch-teemo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install node-fetch@2

      - name: Buscar dados do Teemo
        run: |
          mkdir -p data
          node scripts/fetch_teemo.js
        env:
          RIOT_API_KEY: ${{ secrets.riot_api_key }}

      - name: Commit e push dos dados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/teemo.json
          git commit -m "Atualizar dados do Teemo"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Sporathus-Fungus/Sporathus-Fungus.github.io.git HEAD:main
        continue-on-error: true